services:
  backend:
    container_name: backend
    image: backend
    build: .
    ports:
      - '8080:8080'

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: pruebas
      POSTGRES_PASSWORD: password
    volumes:
      - "./volumes_postgres:/var/lib/postgresql/data"
      - "./postgres_database/prueba.sql:/docker-entrypoint-initdb.d/prueba.sql"
      - "./postgres_database/data_prueba.sql:/docker-entrypoint-initdb.d/data_prueba.sql"
    ports:
      - '5432:5432'
    
