services:
  backend:
    container_name: backend
    image: backend
    build: .
    ports:
      - '8080:8080'

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    
